### ISSUE TITLE
Maybe a Bug? -> "Test-AccessToken : A parameter cannot be found that matches parameter name 'eq'."

### ISSUE THREAD

**Issue by Klotzzz** [MSEndpointMgr/IntuneWin32App#119]
Hello there,

i think i may have found a tiny bug. But i'm not a big of a powershell genius, so maybe i am just doing something wrong.

Anyway, here is what i observed:

The file IntuneWin32App\1.4.2\Public\New-IntuneWin32AppDependency.ps1 gives the following error:

####################
Test-AccessToken : A parameter cannot be found that matches parameter name 'eq'.
At C:\Program Files\WindowsPowerShell\Modules\IntuneWin32App\1.4.2\Public\New-IntuneWin32AppDependency.ps1:42 char:34
             if (Test-AccessToken -eq $false) {
                                  ~~~
    + CategoryInfo          : InvalidArgument: (:) [Test-AccessToken], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Test-AccessToken
####################

The Code behind is:

{
            if (Test-AccessToken -eq $false) {
                Write-Warning -Message "Existing token found but has expired, use Connect-MSIntuneGraph to request a new authentication token"; break
            }
####################

And the command "(Test-AccessToken -eq $false)" indeed gives the error "Test-AccessToken : A parameter cannot be found that matches parameter name 'eq'."

 -->> But it worked with "((Test-AccessToken) -eq $false)"  :)



Btw-
this is my first post on github

**Comment by kevinprow** [comment]
I can confirm this behavior and solution... when Test-AccessToken is put into a variable vs a cmdlet before comparison, it works.

**Comment by DennisBergemann** [comment]
Already solved by another ticket. Fixed in 1.44

**Comment by Klotzzz** [comment]
> Already solved by another ticket. Fixed in 1.44

Can you name the ticket please?
i reinstalled with 1.4.4 an still have this behavior.

Tanks in advance
M

**Comment by DennisBergemann** [comment]
Hi @Klotzzz 

i did it by myself in my own repository, but in my ticket where i gave insights, they told me to fix this

**Comment by Klotzzz** [comment]
@DennisBergemann 

Thx :)
